---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneRole
metadata:
  name: edpm-compute
  namespace: openstack
spec:
  nodeTemplate:
    networkConfig:
      template: _EDPM_NETWORK_CONFIG_TEMPLATE_
    managed: false
    managementNetwork: ctlplane
    ansibleUser: root
    ansiblePort: 22
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
    ansibleVars: |
      registry_name: "quay.io"
      registry_namespace: "tripleozedcentos9"
      image_tag: "current-tripleo"
      edpm_ovn_controller_agent_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-ovn-controller:{{ image_tag }}"
      edpm_iscsid_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-iscsid:{{ image_tag }}"
      edpm_logrotate_crond_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-cron:{{ image_tag }}"
      edpm_ovn_metadata_agent_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-neutron-metadata-agent-ovn:{{ image_tag }}"

      gather_facts: false
      enable_debug: false

      epdm_chrony_ntp_servers:
      - '_EDPM_CHRONY_NTP_SERVER_'

      # 99-standalone-vars
      ctlplane_dns_nameservers:
      - 192.168.122.1
      dns_search_domains: []
      edpm_ovn_dbs:
      - _EDPM_OVN_DBS_

      # edpm firewall, change the allowed CIDR if needed
      edpm_sshd_configure_firewall: true
      edpm_sshd_allowed_ranges: _EDPM_SSHD_ALLOWED_RANGES_
      # SELinux module
      edpm_selinux_mode: enforcing
      undercloud_hosts_entries: []
      # edpm_hosts_entries role
      extra_hosts_entries:
      - 172.17.0.80 glance-internal.openstack.svc neutron-internal.openstack.svc cinder-internal.openstack.svc nova-internal.openstack.svc placement-internal.openstack.svc keystone-internal.openstack.svc
      - 172.17.0.85 rabbitmq.openstack.svc
      - 172.17.0.86 rabbitmq-cell1.openstack.svc
      vip_hosts_entries: []
      hosts_entries: []
      hosts_entry: []
      plan: overcloud
---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNode
metadata:
  name: edpm-compute-0
  namespace: openstack
spec:
  role: edpm-compute
  hostName: edpm-compute-0
  ansibleHost: _COMPUTE_IP_
  node:
    networks:
      - network: ctlplane
        fixedIP: _COMPUTE_IP_
    ansibleUser: root
    openStackAnsibleEERunnerImage: _OPENSTACK_RUNNER_IMG_
    ansibleVars: |
      ansible_ssh_user: root
      ctlplane_ip: _COMPUTE_IP_
      internal_api_ip: 192.168.24.2
      tenant_ip: _COMPUTE_IP_
      fqdn_internal_api: '{{ ansible_fqdn }}'
      service_net_map:
        nova_api_network: internal_api
        nova_libvirt_network: internal_api

      # edpm_network_config
      # Default nic config template for a EDPM compute node
      # These vars are edpm_network_config role vars
      edpm_network_config_hide_sensitive_logs: false
      #
      # These vars are for the network config templates themselves and are
      # considered EDPM network defaults.
      neutron_physical_bridge_name: br-ex
      neutron_public_interface_name: eth0
      ctlplane_mtu: 1500
      ctlplane_subnet_cidr: 24
      ctlplane_gateway_ip: 192.168.122.1
      ctlplane_host_routes:
      - ip_netmask: 0.0.0.0/0
        next_hop: 192.168.122.1
      external_mtu: 1500
      external_vlan_id: 44
      external_cidr: '24'
      external_host_routes: []
      internal_api_mtu: 1500
      internal_api_vlan_id: 20
      internal_api_cidr: '24'
      internal_api_host_routes: []
      storage_mtu: 1500
      storage_vlan_id: 21
      storage_cidr: '24'
      storage_host_routes: []
      tenant_mtu: 1500
      tenant_vlan_id: 22
      tenant_cidr: '24'
      tenant_host_routes: []
      role_networks:
      - InternalApi
      - Storage
      - Tenant
      networks_lower:
        External: external
        InternalApi: internal_api
        Storage: storage
        Tenant: tenant

      # edpm_nodes_validation
      edpm_nodes_validation_validate_controllers_icmp: false
      edpm_nodes_validation_validate_gateway_icmp: false

      edpm_ovn_metadata_agent_DEFAULT_transport_url: '_EDPM_OVN_METADATA_AGENT_TRANSPORT_URL_'
      edpm_ovn_metadata_agent_metadata_agent_ovn_ovn_sb_connection: '_EDPM_OVN_METADATA_AGENT_SB_CONNECTION_'
      edpm_ovn_metadata_agent_metadata_agent_DEFAULT_nova_metadata_host: '_EDPM_OVN_METADATA_AGENT_NOVA_METADATA_HOST_'
      edpm_ovn_metadata_agent_metadata_agent_DEFAULT_metadata_proxy_shared_secret: '_EDPM_OVN_METADATA_AGENT_PROXY_SHARED_SECRET_'
      edpm_ovn_metadata_agent_DEFAULT_bind_host: '_EDPM_OVN_METADATA_AGENT_BIND_HOST_'
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
  deployStrategy:
    deploy: true
